version: "3.7"

services:
  app:
    image: golang:1.14-alpine
    # Comment out this first version of 'command' for development (live-reloading)
    # command: sh -c './wait-for mysql:3306 -- go get github.com/cespare/reflex && reflex -c reflex.conf'
    command: sh -c 'go mod tidy && go run .'
    ports:
      - 3000:3000
    depends_on:
      - mysql
    working_dir: /app
    volumes:
      - ./:/app
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
      MYSQL_DB: books
      # Comment out the following line to clear the database when live-reloading
      # CLEAR_DB_ON_RELOAD: "on"
      # Comment out the following line to activate upper-db debug logs
      # UPPERIO_DB_DEBUG: 1

  mysql:
    image: mysql:5.7
    command: --max_allowed_packet=268435456
    volumes:
      - books-mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: books

volumes:
  books-mysql-data: